services:
  app:
    build: .
    container_name: autocomplete-agent
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules # Stope local node_modules from overwriting container node_modules
    ports:
      - "6080:6080"
    restart: unless-stopped
